apiVersion: v1
kind: Service
metadata:
  name: python-backend-service
spec:
  selector:
    app: python-backend
  type: NodePort
  ports:
    - name: http
      port: 5000         # Service port
      targetPort: 5000   # Container port
      nodePort: 30500    # External port (must be between 30000-32767)